name: "MinIO"
slug: "minio"
version: "1.0.0"
description: "S3-compatible object storage addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: minio/minio:latest
startup: "services"
tempfs: true
ports:
  9000/tcp: 9000
map:
  - share:rw