name: "MinIO"
slug: "minio"
version: "0.0.6"
description: "S3-compatible object storage addon"
arch:
  - amd64
startup: "services"
tempfs: true
ports:
  9000/tcp: 9000
  9001/tcp: 9001
environment:
  MINIO_ROOT_USER: "admin"
  MINIO_ROOT_PASSWORD: "password"
map:
  - share:rw