name: "MinIO"
slug: "minio"
version: "0.0.10"
description: "S3-compatible object storage addon"
arch:
  - amd64
startup: "services"
tempfs: true
ports:
  9000/tcp: 9000
  9001/tcp: 9001
options:
  root_user: "admin"
  root_password: "password"
environment:
  MINIO_ROOT_USER: "{root_user}"
  MINIO_ROOT_PASSWORD: "{root_password}"
map:
  - share:rw