FROM minio/minio:latest

COPY bashio /tmp/bashio

CMD ["server", "/share/raid1/MinIO", "--console-address", ":9001"]

#curl -J -L -o /tmp/bashio.tar.gz \
#    "https://github.com/hassio-addons/bashio/archive/${BASHIO_VERSION}.tar.gz" \
#    && mkdir /tmp/bashio \
#    && tar zxvf \
#    /tmp/bashio.tar.gz \
#    --strip 1 -C /tmp/bashio \
#    \
#    && mv /tmp/bashio/lib /usr/lib/bashio \
#    && ln -s /usr/lib/bashio/bashio /usr/bin/bashio